package com.example.familytree.ui.theme

object HebrewText {

    const val LOAD_MEMBERS_FROM_FIREBASE = "משוך נתונים מה-firebase"
    const val SUCCESS_LOADING_MEMBER_MAP = "בני משפחה נמשכו בהצלחה מה-firebase"
    const val ERROR_LOADING_MEMBER_MAP = "שגיאה בטעינת בני משפחה"
    const val SHOW_ALL_FAMILY_MEMBERS = "הצג את כל בני המשפחה"
    const val REMOVE = "הסר"
    const val ADD_NEW_FAMILY_MEMBER = "הוסף בן משפחה חדש"
    const val FAILED_TO_CONNECT_TO_FIREBASE = "שגיאה בגישה ל-firebase, אולי כדאי לבדוק חיבור לאינטרנט"
    const val SUCCESS_ADDING_MEMBER = "בן משפחה נוסף בהצלחה"
    const val TO = "ל"
    const val ERROR_ADDING_MEMBER = "הוספת בן משפחה נכשלה"
    const val FAMILY_MEMBER_LIST = "רשימת בני משפחה"
    const val UNKNOWN = "לא ידוע"
    const val RABBI = "הרב "
    const val FAMILY_MEMBER_DETAILS = "פרטי בן משפחה"
    const val MARRIED_COUPLE_CAN_NOT_BE_OF_SAME_SEX = "זוג נשוי אינם יכולים להיות מאותו המין"
    const val EXISTS_ALREADY_FAMILY_RELATION_OF_TYPE = "קיים כבר קשר משפחתי מסוג "
    const val CLOSE = "סגור"
    const val CAN_NOT_ADD = "לא ניתן להוסיף את "
    const val BECAUSE = "מכיוון ש"
    const val AS = "כ"
    const val HE = "הוא"
    const val SHE = "היא"
    const val OK = "אישור"
    const val CHOOSE_FAMILY_MEMBER_TYPE = "בחר סוג בן משפחה"
    const val FAMILY_MEMBER_TYPE = "סוג בן משפחה"
    const val YESHIVA_FAMILY_MEMBER = "בן משפחה מהישיבה"
    const val NON_YESHIVA_FAMILY_MEMBER = "בן משפחה שאינו מהישיבה"
    const val ADD_FAMILY_MEMBER = "הוסף בן משפחה"
    const val CONTINUE = "המשך"
    const val CANCEL = "בטל"
    const val IS_THIS_FAMILY_MEMBER_A_RABBI = "האם בן משפחה זה הוא רב?"
    const val FIRST_NAME = "שם פרטי"
    const val LAST_NAME = "שם משפחה"
    const val SEX = "מין"
    const val MALE = "זכר"
    const val FEMALE = "נקבה"
    const val YES = "כן"
    const val NO = "לא"
    const val MACHZOR = "מחזור"
    const val NEW_FAMILY_MEMBERS_MUST_BE_RELATED_TO_AN_EXISTING_MEMBER = "בני משפחה חדשים נדרשים להיות קשורים לבן משפחה קיים בעץ."
    const val TO_WHICH_EXISTING_MEMBER_IS_YOUR_NEW_MEMBER_CONNECTED_TO = "לאיזה בן משפחה בעץ, מקושר בן המשפחה שאתה רוצה להוסיף?"
    const val CHOOSE_FAMILY_MEMBER = "בחר בן משפחה"
    const val CHOOSE_RELATION = "בחר קשר משפחתי"
    const val MARRIED_TO = "נשוי ל"
    const val FATHER_OF = "אבא של "
    const val MOTHER_OF = "אמא של "
    const val SON_OF = "בן של "
    const val DAUGHTER_OF = "בת של"
    const val GRANDMOTHER_OF = "סבתא של "
    const val GRANDFATHER_OF = "סבא של "
    const val GRANDSON_OF = "נכד של "
    const val GRANDDAUGHTER_OF = "נכדה של "
    const val COUSIN_OF = "בן דוד / בת דודה של "
    const val SIBLING_OF = "אח / אחות של "

}